power:
  #this is in minutes
  onlineTime: 60
  #this is in minutes
  offlineTime: 60
  #this is in hours
  offlineTimer: 1
  online: 2
  offline: 1
  deathLoss: 1
  #5 power per chunk
  powerToChunkRatio: 5
farm:
  #out of 100
  percentFarmablePerChunk: 50
