power:
  #this is in minutes
  onlineTime: 60
  #this is in minutes
  offlineTime: 60
  #this is in hours
  offlineTimer: 1
  online: 2
  offline: 1
  deathLoss: 1
  #5 power per chunk
  powerToChunkRatio: 5
farm:
  #out of 100
  percentFarmablePerChunk: 50
sign:
  signCreationKey: "[gang]"
  #this is in seconds
  rotationTime: 5
  noAlerts: "No alerts active"
  #all these lines get the same replace calls
  firstLine: "{gang} Coordinates"
  secondLine: "X: {x}"
  thirdLine: "Y: {y}"
  fourthLine: "Z: {z}"
